[package]
name = "catport"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.44", features = ["derive"] }
serde = "1.0.219"
serde_json = "1.0.142"
syntect = "5.2.0"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
